### ISSUE TITLE
Edit Mail List shows blank settings

### ISSUE THREAD

**Issue by gogglespisano** [grommunio/admin-web#1]
After creating a Mail List, selecting Edit for the mail list opens the settings dialog, however, the current settings are missing/blank.

The same settings as a new mail list is displayed.

**Comment by StefanAkie** [comment]
Has been resolved with latest commit

**Comment by gogglespisano** [comment]
Is the change in admin-web?  I don't see the change for it.  Has it not been merged yet?

**Comment by jengelh** [comment]
(git mirror propagation delay)

**Comment by gogglespisano** [comment]
I see it now.

How do I update my installation to try this fix?

**Comment by jengelh** [comment]
https://docs.grommunio.com/admin/operations.html#updating-grommunio
